### PR TITLE
Add railtie

### PR DESCRIPTION
**Pull request by bion**

### CODE REVIEW

**Comment by dbalatero** [comment]
@cohitre if you want to give me commit access I can take care of PRs and merging as well on this?

**Comment by dbalatero** [comment]
This is related to a project @bion and i are working on

**Comment by cohitre** [comment]
you got it.

**Comment by dbalatero** [comment]
@bion if you write docs, I can merge this

**Comment by bion** [comment]
@dbalatero aha, will do

**Comment by dbalatero** [comment]
@bion FYI you have multiple PRs open – one on your fork, and one on this one.

**Pull request merged**
